enabled: true
startAtEnd: false

file:
    path: /tomcat/logs
    nameGlob: cart.log

multiline:
   startsWith: "["

fields:
   sourceType: ECommerce41-log4j
   nodeName: _NODE_NAME
   tierName: _TIER_NAME
   appName: _APP_NAME

grok:
  patterns:
    - "\\[%{LOGLEVEL:logLevel}%{SPACE}\\]  \\[%{DATA:threadName}\\]  \\[%{JAVACLASS:class}\\]  \\[AD_REQUEST_GUID\\[%{DATA:requestGUID}\\]\\]  %{GREEDYDATA:logMessage}"

eventTimestamp:
   pattern: "yyyy-MM-dd HH:mm:ss,SSS"
